import * as dotenv from 'dotenv';
dotenv.config();


import Footer from '@/components/footer/footer';
import Header from '@/components/header/header';
import './globals.css';

import { Rajdhani } from 'next/font/google';

const rajdhani = Rajdhani({
  weight: "500",
  subsets: ["latin"]

})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rajdhani.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}