import Link from 'next/link'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header />
      <body>{children}</body>
      <Footer />
    </html>
  )
}


function Header() {
  return (
    <header>
      <section>LOGO</section>
      <section>
        <nav>
          <ul>
            <li><Link href="/#who">Who</Link></li>
            <li><Link href="/#who">Education</Link></li>
            <li><Link href="/#who">Professional</Link></li>
            <li><Link href="/#who">Personal</Link></li>
          </ul>
        </nav>
      </section>
      <section>

      </section>
    </header>
  );
}

function Footer() {
  return (
    <footer>
      <section>
        <p>copyrights reserved ©</p>
      </section>
      <section>
        <Link href="/#who">Contact</Link>
      </section>
    </footer>
  );
}