import * as dotenv from 'dotenv';
dotenv.config();

import Footer from '@/components/layout/footer';
import Header from '@/components/layout/header';
import './globals.css';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}